cyllene_digital_sylius_advanced_taxon_admin_facet_preview:
    path: /advanced-taxon/facet-conditions/preview
    methods: [POST]
    defaults:
        _controller: CylleneDigital\SyliusAdvancedTaxonPlugin\Controller\AdminFacetPreviewController
